'use client';

import React, { useState, useRef, useEffect } from 'react';
import useSWR from 'swr';
import { useToast } from '@/components/toast-provider';
import {
    UserPlus, Search, Star, Clock, BadgeCheck,
    Edit2, Gift, Banknote, Receipt, Settings,
    Phone, Calendar, X
} from 'lucide-react';

const fetcher = (url: string) => fetch(url).then(r => r.json());

// Create/Edit Member Modal
const MemberModal = ({ member, onClose, onSave }: { member?: any, onClose: () => void, onSave: () => void }) => {
    const isEdit = !!member;
    const nameInputRef = useRef<HTMLInputElement>(null);
    const [formData, setFormData] = useState({
        memberCode: member?.memberCode || `M${Date.now().toString().slice(-6)}`,
        fullName: member?.fullName || '',
        phone: member?.phone || '',
        tier: member?.tier || 'BRONZE'
    });
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Auto-focus on full name input when modal opens
    useEffect(() => {
        nameInputRef.current?.focus();
    }, []);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);

        try {
            const url = isEdit ? `/api/members/${member.id}` : '/api/members/create';
            const method = isEdit ? 'PATCH' : 'POST';

            // For new members, don't send memberCode (backend generates it)
            const payload = isEdit
                ? formData
                : { fullName: formData.fullName, phone: formData.phone, tier: formData.tier };

            const res = await fetch(url, {
                method,
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) throw new Error('Failed to save');
            onSave();
        } catch (error) {
            alert('Gagal menyimpan member');
            console.error(error);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-xl w-full max-w-md overflow-hidden">
                <div className="p-4 border-b border-[var(--border-default)] bg-[var(--bg-card)] flex justify-between items-center">
                    <h3 className="text-lg font-bold text-[var(--text-primary)]">{isEdit ? 'Edit Member' : 'Tambah Member Baru'}</h3>
                    <button onClick={onClose} className="text-[var(--text-muted)] hover:text-[var(--text-primary)]"><X size={20} /></button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-4">
                    <div>
                        <label className="text-xs text-[var(--text-muted)] uppercase font-bold block mb-1">Kode Member</label>
                        <input
                            type="text"
                            value={formData.memberCode}
                            disabled
                            placeholder="Auto-generated by system"
                            className="w-full bg-[var(--bg-base)] border border-[var(--border-default)] rounded p-2 text-[var(--text-muted)] text-sm outline-none font-mono opacity-60 cursor-not-allowed"
                        />
                    </div>

                    <div>
                        <label className="text-xs text-[var(--text-muted)] uppercase font-bold block mb-1">Nama Lengkap</label>
                        <input
                            ref={nameInputRef}
                            type="text"
                            required
                            value={formData.fullName}
                            onChange={e => setFormData({ ...formData, fullName: e.target.value })}
                            className="w-full bg-[var(--bg-base)] border border-[var(--border-default)] rounded p-2 text-[var(--text-primary)] text-sm focus:border-[var(--accent-primary)] outline-none"
                        />
                    </div>

                    <div>
                        <label className="text-xs text-[var(--text-muted)] uppercase font-bold block mb-1">No. Telepon</label>
                        <input
                            type="tel"
                            required
                            value={formData.phone}
                            onChange={e => setFormData({ ...formData, phone: e.target.value })}
                            className="w-full bg-[var(--bg-base)] border border-[var(--border-default)] rounded p-2 text-[var(--text-primary)] text-sm focus:border-[var(--accent-primary)] outline-none"
                        />
                    </div>

                    <div>
                        <label className="text-xs text-[var(--text-muted)] uppercase font-bold block mb-1">Tier</label>
                        <select
                            value={formData.tier}
                            onChange={e => setFormData({ ...formData, tier: e.target.value })}
                            className="w-full bg-[var(--bg-base)] border border-[var(--border-default)] rounded p-2 text-[var(--text-primary)] text-sm focus:border-[var(--accent-primary)] outline-none"
                        >
                            <option value="BRONZE">Bronze</option>
                            <option value="SILVER">Silver</option>
                            <option value="GOLD">Gold</option>
                        </select>
                    </div>

                    <button
                        type="submit"
                        disabled={isSubmitting}
                        className="w-full py-3 bg-[var(--accent-primary)] hover:bg-[#16a34a] text-black font-bold rounded-lg disabled:opacity-50"
                    >
                        {isSubmitting ? 'Menyimpan...' : (isEdit ? 'Simpan Perubahan' : 'Tambah Member')}
                    </button>
                </form>
            </div>
        </div>
    );
};

export default function MembersPage() {
    const { showToast } = useToast();
    const [selectedId, setSelectedId] = useState<number | null>(null);
    const [activeTab, setActiveTab] = useState<'history' | 'rewards' | 'settings'>('history');
    const [search, setSearch] = useState('');
    const [showModal, setShowModal] = useState(false);
    const [editingMember, setEditingMember] = useState<any>(null);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

    // Fetch Members
    const { data: membersData, mutate } = useSWR(
        `/api/members?q=${search}`,
        fetcher
    );

    // Fetch detailed member data
    const { data: memberDetailData } = useSWR(
        selectedId ? `/api/members/${selectedId}` : null,
        fetcher
    );

    const members = membersData?.data || [];
    const selectedMember = memberDetailData?.data || members.find((m: any) => m.id === selectedId) || members[0];

    // Calculate stats from detailed member data
    const memberStats = selectedMember ? {
        totalVisits: selectedMember.sessions?.length || 0,
        totalSpent: selectedMember.orders?.reduce((sum: number, order: any) => sum + Number(order.totalAmount || 0), 0) || 0,
        pointsEarned: selectedMember.transactions?.filter((t: any) => t.type === 'EARN').reduce((sum: number, t: any) => sum + t.amount, 0) || 0,
        pointsRedeemed: selectedMember.transactions?.filter((t: any) => t.type === 'REDEEM').reduce((sum: number, t: any) => sum + Math.abs(t.amount), 0) || 0
    } : null;

    React.useEffect(() => {
        if (!selectedId && members.length > 0) {
            setSelectedId(members[0].id);
        }
    }, [members, selectedId]);

    const getTierColor = (tier: string) => {
        switch (tier) {
            case 'GOLD': return 'text-[var(--accent-secondary)] bg-[#eab308]/20 border-[#eab308]/30';
            case 'SILVER': return 'text-slate-300 bg-slate-700 border-slate-600';
            case 'BRONZE': return 'text-[#f97316] bg-[#f97316]/20 border-[#f97316]/30';
            default: return 'text-[var(--text-muted)] bg-slate-800 border-slate-700';
        }
    };

    const handleDeleteMember = async () => {
        if (!selectedId) return;

        try {
            const res = await fetch(`/api/members/${selectedId}`, { method: 'DELETE' });
            if (!res.ok) throw new Error('Failed to delete member');

            setSelectedId(null);
            mutate();
            setShowDeleteConfirm(false);
            showToast('success', 'Member berhasil dihapus');
        } catch (error) {
            console.error(error);
            showToast('error', 'Gagal menghapus member');
        }
    };

    return (
        <div className="flex flex-1 overflow-hidden relative h-full">
            {/* Sidebar */}
            <aside className="w-[400px] bg-[var(--bg-surface)] border-r border-[var(--border-default)] flex flex-col shrink-0 z-10">
                <div className="p-4 border-b border-[var(--border-default)] space-y-4">
                    <div className="flex justify-between items-center">
                        <h3 className="font-bold text-lg text-[var(--text-primary)]">Daftar Member</h3>
                        <button
                            onClick={() => { setEditingMember(null); setShowModal(true); }}
                            className="flex items-center gap-2 bg-[var(--accent-primary)] hover:bg-[#16a34a] text-black text-sm font-bold py-1.5 px-3 rounded transition-colors"
                        >
                            <UserPlus size={18} /> Baru
                        </button>
                    </div>
                    <div className="relative group">
                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] group-focus-within:text-[var(--accent-primary)]">
                            <Search size={20} />
                        </span>
                        <input
                            className="w-full bg-[var(--bg-base)] border border-[var(--border-default)] rounded py-2 pl-10 pr-4 text-sm text-[var(--text-primary)] focus:ring-1 focus:ring-[#f07000] focus:border-[var(--accent-primary)] placeholder:text-slate-600 outline-none"
                            placeholder="Cari nama, ID, atau no HP..."
                            type="text"
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                        />
                    </div>
                    <div className="flex gap-2 overflow-x-auto no-scrollbar pb-1">
                        <button className="bg-[var(--accent-primary)]/20 border border-[var(--accent-primary)] text-[var(--accent-primary)] px-3 py-1 rounded text-xs font-medium whitespace-nowrap">Semua</button>
                        {['VIP Gold', 'Silver', 'Expired'].map(filter => (
                            <button key={filter} className="bg-[var(--bg-base)] border border-[var(--border-default)] text-[var(--text-muted)] hover:text-[var(--text-primary)] px-3 py-1 rounded text-xs font-medium whitespace-nowrap transition-colors">
                                {filter}
                            </button>
                        ))}
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-3 space-y-2">
                    {members.map((member: any) => (
                        <div
                            key={member.id}
                            onClick={() => setSelectedId(member.id)}
                            className={`group flex gap-3 p-3 border rounded cursor-pointer relative overflow-hidden transition-all
                  ${selectedId === member.id
                                    ? 'bg-[var(--bg-card)] border-[var(--accent-primary)]/50'
                                    : 'bg-[var(--bg-base)] border-[var(--border-default)] hover:bg-[var(--bg-card)] hover:border-[var(--border-default)]/80'
                                }
                `}
                        >
                            {selectedId === member.id && <div className="absolute left-0 top-0 bottom-0 w-1 bg-[var(--accent-primary)]"></div>}
                            <div className="w-12 h-12 rounded bg-slate-800 shrink-0 flex items-center justify-center font-bold text-[var(--text-muted)] border border-[var(--border-default)]">
                                {member.fullName.substring(0, 2).toUpperCase()}
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="flex justify-between items-start mb-1">
                                    <h4 className={`font-bold text-sm truncate ${selectedId === member.id ? 'text-[var(--text-primary)]' : 'text-slate-300 group-hover:text-[var(--text-primary)]'}`}>
                                        {member.fullName}
                                    </h4>
                                    <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${getTierColor(member.tier)}`}>
                                        {member.tier}
                                    </span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">ID: {member.memberCode}</p>
                                <div className="flex items-center gap-4 text-xs">
                                    <span className={`flex items-center gap-1 ${selectedId === member.id ? 'text-[var(--accent-primary)]' : 'text-[var(--text-muted)]'}`}>
                                        <Star size={14} /> {member.pointsBalance.toLocaleString()} Poin
                                    </span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </aside>

            {/* Main Content */}
            {selectedMember ? (
                <main className="flex-1 flex flex-col h-full bg-[var(--bg-base)] overflow-hidden relative">
                    {/* Header Gradient */}
                    <div className="absolute top-0 left-0 right-0 h-48 bg-gradient-to-b from-[#0f1a14] to-[#050a07] z-0 border-b border-[var(--border-default)]"></div>

                    {/* Profile Header */}
                    <div className="relative z-10 px-8 pt-8 pb-6 flex items-end justify-between">
                        <div className="flex items-end gap-6">
                            <div className="size-32 rounded-lg border-4 border-[#050a07] bg-slate-800 flex items-center justify-center shadow-lg">
                                <span className="text-4xl font-bold text-[var(--text-muted)]">{selectedMember.fullName.substring(0, 2).toUpperCase()}</span>
                            </div>
                            <div className="pb-2">
                                <div className="flex items-center gap-3 mb-1">
                                    <h1 className="text-3xl font-bold text-[var(--text-primary)]">{selectedMember.fullName}</h1>
                                    <BadgeCheck size={24} className="text-[var(--accent-secondary)]" />
                                </div>
                                <div className="flex items-center gap-4 text-sm text-[var(--text-muted)] mb-2">
                                    <span>ID: <span className="text-[var(--text-primary)] font-mono">{selectedMember.memberCode}</span></span>
                                    <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
                                    <span>Bergabung: <span className="text-[var(--text-primary)]">{new Date(selectedMember.joinDate).toLocaleDateString()}</span></span>
                                    <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
                                    <span>No. HP: <span className="text-[var(--text-primary)]">{selectedMember.phone}</span></span>
                                </div>
                                <div className="flex gap-2">
                                    <span className={`text-xs font-bold px-2 py-1 rounded border ${getTierColor(selectedMember.tier)}`}>
                                        {selectedMember.tier} MEMBER
                                    </span>
                                    {selectedMember.status === 'ACTIVE' && (
                                        <span className="bg-[var(--accent-primary)]/10 text-[var(--accent-primary)] text-xs font-bold px-2 py-1 rounded border border-[var(--accent-primary)]/20">AKTIF</span>
                                    )}
                                </div>
                            </div>
                        </div>

                        <div className="flex gap-2 pb-2">
                            <button
                                onClick={() => { setEditingMember(selectedMember); setShowModal(true); }}
                                className="flex items-center gap-1.5 bg-[var(--bg-surface)] hover:bg-[var(--bg-card)] border border-[var(--border-default)] text-[var(--text-primary)] px-3 py-1.5 rounded text-sm font-medium transition-colors"
                            >
                                <Edit2 size={16} /> Edit Profil
                            </button>
                            <button
                                onClick={() => setShowDeleteConfirm(true)}
                                className="flex items-center gap-1.5 bg-red-500/10 hover:bg-red-500/20 border border-red-500/30 text-red-500 px-3 py-1.5 rounded text-sm font-medium transition-colors"
                            >
                                <X size={16} /> Hapus Member
                            </button>
                            <button
                                className="flex items-center gap-1.5 bg-[#eab308] hover:bg-yellow-500 text-black px-3 py-1.5 rounded text-sm font-bold border border-yellow-600 transition-colors shadow-none"
                            >
                                <Gift size={16} /> Tukar Reward
                            </button>
                        </div>
                    </div>

                    {/* Stats Grid */}
                    <div className="relative z-10 px-8 mb-6">
                        <div className="grid grid-cols-4 gap-4">
                            <div className="bg-[var(--bg-surface)] border border-[var(--border-default)] p-4 rounded flex flex-col">
                                <span className="text-[var(--text-muted)] text-xs uppercase font-bold tracking-wider mb-1">Sisa Poin</span>
                                <div className="flex items-end justify-between">
                                    <span className="text-3xl font-bold text-[var(--accent-primary)]">{selectedMember.pointsBalance.toLocaleString()}</span>
                                    <Star className="text-[var(--accent-primary)]/30" size={32} />
                                </div>
                            </div>
                            <div className="bg-[var(--bg-surface)] border border-[var(--border-default)] p-4 rounded flex flex-col">
                                <span className="text-[var(--text-muted)] text-xs uppercase font-bold tracking-wider mb-1">Total Kunjungan</span>
                                <div className="flex items-end justify-between">
                                    <span className="text-3xl font-bold text-[var(--text-primary)]">{memberStats?.totalVisits || 0}</span>
                                    <Clock className="text-slate-700" size={32} />
                                </div>
                            </div>
                            <div className="bg-[var(--bg-surface)] border border-[var(--border-default)] p-4 rounded flex flex-col">
                                <span className="text-[var(--text-muted)] text-xs uppercase font-bold tracking-wider mb-1">Total Belanja</span>
                                <div className="flex items-end justify-between">
                                    <span className="text-2xl font-bold text-[var(--text-primary)]">Rp {memberStats?.totalSpent ? (memberStats.totalSpent / 1000000).toFixed(1) + 'jt' : '0'}</span>
                                    <Banknote className="text-slate-700" size={32} />
                                </div>
                            </div>
                            <div className="bg-[var(--bg-surface)] border border-[var(--border-default)] p-4 rounded flex flex-col relative overflow-hidden">
                                <span className="text-[var(--text-muted)] text-xs uppercase font-bold tracking-wider mb-1">Status Tier</span>
                                <div className="relative z-10">
                                    <span className="text-lg font-bold text-[var(--accent-secondary)]">{selectedMember.tier}</span>
                                    <div className="w-full bg-slate-800 h-1.5 rounded-full mt-2 overflow-hidden">
                                        <div className="bg-[#eab308] h-full w-[65%]"></div>
                                    </div>
                                    <span className="text-[10px] text-[var(--text-muted)] mt-1 block">Poin: {selectedMember.pointsBalance}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Tabs */}
                    <div className="px-8 border-b border-[var(--border-default)] flex gap-8 mb-0">
                        {[
                            { id: 'history', label: 'Riwayat Transaksi', icon: Receipt },
                            { id: 'rewards', label: 'Katalog Reward', icon: Gift },
                            { id: 'settings', label: 'Pengaturan', icon: Settings },
                        ].map((tab) => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id as any)}
                                className={`pb-3 border-b-2 font-medium text-sm flex items-center gap-2 transition-colors
                  ${activeTab === tab.id
                                        ? 'border-[var(--accent-primary)] text-[var(--accent-primary)]'
                                        : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-primary)]'
                                    }
                `}
                            >
                                <tab.icon size={18} />
                                {tab.label}
                            </button>
                        ))}
                    </div>

                    {/* Tab Content */}
                    <div className="flex-1 overflow-y-auto p-8 bg-[var(--bg-base)]">
                        {activeTab === 'history' && (
                            <div className="rounded border border-[var(--border-default)] overflow-hidden bg-[var(--bg-surface)]">
                                <div className="p-8 text-center text-[var(--text-muted)]">
                                    Tidak ada riwayat transaksi.
                                </div>
                            </div>
                        )}
                        {activeTab !== 'history' && (
                            <div className="flex flex-col items-center justify-center h-full text-[var(--text-muted)] pb-20">
                                <Settings size={32} className="opacity-50 mb-4" />
                                <p>Fitur {activeTab === 'rewards' ? 'Katalog Reward' : 'Pengaturan'} belum tersedia.</p>
                            </div>
                        )}
                    </div>
                </main>
            ) : (
                <main className="flex-1 flex items-center justify-center text-[var(--text-muted)]">
                    Pilih member untuk melihat detail
                </main>
            )}

            {showModal && (
                <MemberModal
                    member={editingMember}
                    onClose={() => setShowModal(false)}
                    onSave={() => { setShowModal(false); mutate(); }}
                />
            )}

            {/* Delete Confirmation Modal */}
            {showDeleteConfirm && (
                <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                    <div className="bg-[var(--bg-surface)] border border-red-500/30 rounded-xl w-full max-w-md overflow-hidden">
                        <div className="p-6 border-b border-red-500/20 bg-red-500/5">
                            <h3 className="text-xl font-bold text-[var(--text-primary)]">Konfirmasi Hapus Member</h3>
                        </div>
                        <div className="p-6">
                            <p className="text-slate-300 mb-6">
                                Apakah Anda yakin ingin menghapus member <span className="font-bold text-[var(--text-primary)]">{selectedMember?.fullName}</span>?
                            </p>
                            <div className="flex gap-3">
                                <button
                                    onClick={() => setShowDeleteConfirm(false)}
                                    className="flex-1 py-2.5 bg-[var(--bg-elevated)] hover:bg-[var(--bg-card)] text-[var(--text-primary)] rounded font-medium transition-colors"
                                >
                                    Batal
                                </button>
                                <button
                                    onClick={handleDeleteMember}
                                    className="flex-1 py-2.5 bg-red-500 hover:bg-red-600 text-[var(--text-primary)] rounded font-bold transition-colors"
                                >
                                    Ya, Hapus
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
